### ISSUE TITLE
TODO 

### ISSUE THREAD

**Issue by ehmkah** [ehmkah/cas_swa_sad#2]
- [x] fotos hochladen -> @ehmkah, @johndilbert 
- [x] Usecase neu zeichnen -> @johndilbert 
- [ ] Usecase in Tabellenform  -> @johndilbert 
- [x] Verteilungsdiagram   -> @Krigu 
- [x] Bausteinsicht Level0 Level1 abmalen, Level2 (Sallkonfiguration), Level ( -> Christian  
- [X] Level2 für Ticketbaustein -> @Krigu @johndilbert
- [] Level2 für Showverwaltung -> @meierfra 
- [x] Aktivitätsdiagram -> @ehmkah
- [ ] glossar -> alle
- [ ] bereits bestehende Textschnippsel eintippen -> alle
- [X] Bausteinsicht Level 0 (Fotovorlage fehlt noch) -> @krigu
- [ ] Platzierung der Diagrame innerhalb der Bausteinsicht -> alle
- [ ] Risiko kapitel -> alle
