### ISSUE TITLE
TODO Part 2

### ISSUE THREAD

**Issue by Krigu** [ehmkah/cas_swa_sad#3]
- [x] Schnittstellen dokumentieren @meierfra # @FrankMoritz aka The Franks
- [x] Merge Glossar @krigu
- [x] arc kommentare entfernen
- [x] Bausteindiagram @meierfra 
- [x] Algorithmus überlegen @krigu @ye-zhao 
- [x] Titelblatt (Autoren + Version + arc42) => @johndilbert 
- [x] Version Tabelle (Page 2) => @johndilbert 
- [x] Basis Dokumente (Page 2) => @johndilbert  
- [x] Druckerschnittstelle => Kapitel8 => @johndilbert 
  ehmkah: "Was ist hier gemeint?" Was für eine Druckerschnittstelle?
  meierfra: Wie die Tickets ausgedruckt werden. -> Es gibt keine spezielle Druckstrasse sondern die Tickets werden als PDF generiert und standardmässig aus dem Browser ausgedruckt
- [x] Fehlerkonzept => @ehmkah 
- [x] Kapitel 1: Use-Case - Beschreiben => @johndilbert 
- [x] Kapitel 2.2 Organisatorische Randbedingungen => @FrankMoritz 
- [x] Kapitel 2.3 Konventionen (wenig/nichts) => @FrankMoritz 
- [x] Kapitel 3.1: Verweis 5.1 (Kontext-Abgrenzung Baustein Level0) => @meierfra
- [x] Kapitel 3.2: Verweis 7 (Deployment-Diagramm) => @meierfra
- [ ] Kapitel 4 Lösungsstrategie (Algorithmus hier dokumentieren) => @Krigu 
- [x] Kapitel 7 Verteilungssicht Text schreiben => @ehmkah  
- [x] Kapitel 8  @FrankMoritz 
- [x] Kapitel 8.1 Domänenmodell => @ehmkah 
- [ ] Kapitel 9 (Algorithmen) Prototypen beschreiben => @ye-zhao (random strategies) , @Krigu  (cache strategy)
- [x] Kapitel 9 (rest ;-) ) => @FrankMoritz
- [x] Kapitel 10 Qualitätsszenrien @meierfra 
- [x] Kapitel 11 Risiko => @johndilbert
- [ ] Grafiken gemäss Glossar überarbeiten (alle)
# review

für review Hints kann man einen Kommentar mit TODO prefix einfügen. Kommentar in asciidoc http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#comments
- [ ] Dokument reviewen
- [x] Fehlerkonzept => @ye-zhao 
- [x] Kapital 5 => @johndilbert 
- [x] Kapitel 6 => @meierfra
- [x] Kapitel 6 => @ye-zhao 
- [x] Kapitel 8 => @ye-zhao  
- [ ] Kapitel 9 => @Krigu , @meierfra, @ehmkah 
- [x] Kapitel 9 => @meierfra
- [x] Kapitel 10 =>  @FrankMoritz 
- [x] Kapitel 11 Risiko => @meierfra
